### ISSUE TITLE
Empty content with new version

### ISSUE THREAD

**Issue by nmouillet** [eberhardt/moodle-filter_collapsible#3] opened 2015-09-30 12:25 UTC
Thanks for the update in Moodle Plugin Repos but with the new version of the filter, the content of the collapsible region is empty when I deploy the region (the text don't appear anymore in the HTML code of the page). The problem disappears when I replace the new filter.php with the old one.

**Comment by eberhardt** [comment] 2015-09-30 12:34
I cannot reproduce that error. Everything works fine (at least at Moodle 2.9). Which version do you use? What are the steps to reproduce the error?

I have change the id's of the div-tags, so that it's more Moodle-like (`collapsible-#` instead of `collapsible#`). Maybe you are using some code, which interferes. The update process should purge all caches, but maybe you need to do it manually.

**Comment by nmouillet** [comment] 2015-09-30 13:03
I'm on Moodle 2.9.2+ and PHP 5.6.13, the cache are empty.
When I install the last version of the filter:
![capture1](https://cloud.githubusercontent.com/assets/6358307/10193524/f73a42aa-6783-11e5-989c-c7e3cd00d214.PNG)
When I replace the filter.php with the old one:
![capture2](https://cloud.githubusercontent.com/assets/6358307/10193535/05a4f416-6784-11e5-98c5-20aa68bb7e1e.PNG)

The text doesn't appears in HTML so I guess the problem is in the PHP code, I'm not sure of what could interfer with the PHP code.

EDIT: After few tests, it seems that I found the line which makes it work:
$tail = trim(substr($tail, strpos($tail, ']') + 1)); works instead of $tail = $match[2];

**Comment by eberhardt** [comment] 2015-09-30 13:20
Strange... your second image shows, that the div-tag has the id `collapsible`. That should have been at least `collapsible0`. I'm not sure, why it should be like that. Can you check your version.php? Does it say 1.01?

**Comment by nmouillet** [comment] 2015-09-30 13:24
Yes it's beacause it's my own old filter.php which include some custom modification regarding the previous bug report i've made (with the id's), so it's a little bit different than the original old filter.php.

It's seems that the problem comes exactly from $tail = $match[2]; because if I change to $tail = trim(substr($tail, strpos($tail, ']') + 1)); it's all ok. But here's where my PHP knowledge stops...

**Comment by eberhardt** [comment] 2015-09-30 13:32
I don't see why the php works on my machine and not on yours. We have the same code (hopefully) and my regions are fine.

**Comment by eberhardt** [comment] 2015-09-30 13:36
You can do a `var_dump($match);` after the if-clause and see what `preg_match` found.

**Comment by nmouillet** [comment] 2015-09-30 13:40
Here is the output of var_dump($match):

array(3) { [0]=> string(24) "[texte repliable 1]
" [1]=> string(17) "texte repliable 1" [2]=> string(5) "
" } array(3) { [0]=> string(24) "[texte repliable 2]
" [1]=> string(17) "texte repliable 2" [2]=> string(5) "
" } array(3) { [0]=> string(24) "[texte repliable 3]
" [1]=> string(17) "texte repliable 3" [2]=> string(5) "
" } array(3) { [0]=> string(24) "[texte repliable 4]
" [1]=> string(17) "texte repliable 4" [2]=> string(5) "
" }

And here is the text I've put in my TinyMCE Editor:

{collapsible}[texte repliable 1]
TEST 1
{collapsible}

{collapsible}[texte repliable 2]
TEST 2
{collapsible}

{collapsible}[texte repliable 3]
TEST 3
{collapsible}

{collapsible}[texte repliable 4]
TEST 4
{collapsible}

**Comment by eberhardt** [comment] 2015-09-30 13:43
Try `preg_match('/^\[([^\]]+)\](.*)$/', $tail, $match)`. I have php 5.4.44 and can't upgrade (Debian), maybe they changed the behavior of `preg_match`.

**Comment by eberhardt** [comment] 2015-09-30 13:46
I mean: replace the `preg_match` on line 72 with the thing off the last comment.

**Comment by eberhardt** [comment] 2015-09-30 13:48
But it seems, that preg_match don't recognise the characters after the brackets. So maybe it's some coding format issues (utf8 vs. iso/windows). :/

**Comment by nmouillet** [comment] 2015-09-30 13:50
The code 
if (preg_match('/^[([^]]+)](.*)$/', $tail, $match)) {
                    $more = $match[1];
                    $tail = $match[2];
                }
Produces
![capture3](https://cloud.githubusercontent.com/assets/6358307/10194796/ec12d2a0-678a-11e5-865a-bde6003634ca.PNG)

**Comment by eberhardt** [comment] 2015-09-30 13:55
You need to copy the backslashes as well. Be careful `[` and `]` is not the same as  `\[` resp. `\]`.

**Comment by eberhardt** [comment] 2015-09-30 13:55
Uups... wrong button ^^

**Comment by eberhardt** [comment] 2015-09-30 13:57
Basically it's the same as before, but with a `$` after `(.*)` and before the last `/`.

**Comment by nmouillet** [comment] 2015-09-30 14:00
Yes it's ok in the code, the \ don't pass the copy/past in the textbox the first time:
if (preg_match('/^[([^]]+)](.*)$/', $tail, $match)) {
                    $more = $match[1];
                    $tail = $match[2];
                }

EDIT: it seems to be removed on post in github but it's there in the code

**Comment by eberhardt** [comment] 2015-09-30 14:27
So now he doesn't recognise the "[" anymore?

**Comment by eberhardt** [comment] 2015-09-30 14:30
I think, there's strange stuff going on and that's maybe because of encoding. You should set your Server and your texteditor to running on UTF-8.

**Comment by eberhardt** [comment] 2018-06-27 09:24
Closing: No issue/fix (anymore).

**Closed as completed by eberhardt** 2018-06-27 09:24 UTC
